env:
  - GO111MODULE=on
before:
  hooks:
  - go mod tidy
gomod:
  proxy: false

builds:
- env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "7"
  ignore:
  - goos: windows
    goarch: arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{ .Version }}
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^chore:', '^test:', 'Merge pull request', 'Merge branch', 'go mod tidy']

archives:
- name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
  format_overrides:
  - goos: windows
    format: zip
  files:
  - README.md
  - LICENSE

nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  maintainer: 'Abdul Khaliq <a.khaliq@outlook.my>'
  description: Retrieve and manage kubernetes pod logs with filtering & highlighting 
  license: MIT
  formats:
  - deb
  - rpm
  - apk
  contents: 
  - src: /usr/bin/plogs
    dst: /usr/bin/kubectl-plogs
    type: "symlink"