apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: plogs
spec:
  version: {{ .TagName }}
  homepage: https://github.com/kha7iq/plogs
  shortDescription: Retrieve and stream colorized logs from Pods.
  description: |
    Plogs retrieves colorized logs from Pods
    with various filtering and monitoring options.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/kha7iq/plogs/releases/download/{{ .TagName }}/plogs_Darwin_x86_64.tar.gz" .TagName }}
    bin: plogs
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/kha7iq/plogs/releases/download/{{ .TagName }}/plogs_Darwin_arm64.tar.gz" .TagName }}
    bin: plogs
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/kha7iq/plogs/releases/download/{{ .TagName }}/plogs_Linux_x86_64.tar.gz" .TagName }}
    bin: plogs
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/kha7iq/plogs/releases/download/{{ .TagName }}/plogs_Linux_arm64.tar.gz " .TagName }}
    bin: plogs
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/kha7iq/plogs/releases/download/{{ .TagName }}/plogs_Windows_x86_64.zip " .TagName }}
    bin: plogs.exe