name: Build and Release

on:
  push:
    tags:
      - 'v0.[0-9]+.[0-9]'
      
jobs:
  Build-and-Release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
 
      - name: Release Plogs
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
  
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.46